### ISSUE TITLE
Results pane isn't adjusting to display results

### ISSUE THREAD

**Issue by naaronne** [andry-virvich/jira#15]
After adding several filters, the view is obscured, won't resize to accommodate issues.

See this screenshot, there are 2 issues in the blocked filter, but you can't see them in the results pane or resize.

![image](https://user-images.githubusercontent.com/10212075/29087627-84b72310-7c44-11e7-9684-3ec9cc0ad577.png)

**Comment by avyrvich** [comment]
fixed in 0.1.3
