### ISSUE TITLE
UX/UI added too many filters

### ISSUE THREAD

**Issue by Seggr** [andry-virvich/jira#8]
I can not refresh or access the edit button any more, after adding one too many filters
<img width="815" alt="screen shot 2016-04-22 at 12 40 07 pm" src="https://cloud.githubusercontent.com/assets/5712949/14749856/74d2f6f4-0887-11e6-9719-b5feb837b762.png">

**Comment by naaronne** [comment]
I believe this might be similar to my reported issue, https://github.com/andry-virvich/jira/issues/15.

**Comment by avyrvich** [comment]
fixed in 0.1.3
