### ISSUE TITLE
Gigantic images

### ISSUE THREAD

**Issue by bromega** [andry-virvich/jira#9]
I tried to add img{max-height:2em} to bootstrap-min.css but then it broke the plugin.
![screen shot 2016-06-28 at 11 19 09 am](https://cloud.githubusercontent.com/assets/4728876/16421213/39302840-3d22-11e6-8405-5cdeee8179e4.png)

**Comment by andry-virvich** [comment]
hey try this version
[jassist.zip](https://github.com/andry-virvich/jira/files/337665/jassist.zip)

and sorry I don't have time for this project =(
